version: '3.8'
services:
  ai_backend:
    build: .
    container_name: ai_backend
    ports:
      - "8000:8000"

  ui_backend:
    build: .
    container_name: ui_backend
    ports:
      - "8001:8001"
    depends_on:
      - ai_backend
